---
on:
  push:
    tags:
      - 'v*'

jobs:
  upload-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - run: mkdir -p dist/release
      - run: touch dist/release/NOASSETS
      - uses: https://code.forgejo.org/actions/forgejo-release@fc0488c944626f9265d87fbc4dd6c08f78014c63 # v2.7.3
        with:
          direction: upload
          url: https://git.zyria.de
          token: ${{ secrets.ZYRIA_TOKEN }}
