---
name: Ansible Lint
on: # yamllint disable-line rule:truthy
  - pull_request
  - push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Determine reporter type
        run: |
          if [ $GITHUB_EVENT_NAME != "pull_request" ]; then
              echo "REVIEWDOG_REPORTER=github-check" >> $GITHUB_ENV
          else
              echo "REVIEWDOG_REPORTER=github-pr-review" >> $GITHUB_ENV
          fi

      - name: Run ansible-lint
        uses: reviewdog/action-ansiblelint@5b8ca4b12dcbcdf63d4739dacd90609abafe8924 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          level: info
          reporter: ${{ env.REVIEWDOG_REPORTER }}

      - name: Run yamllint
        uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0 # v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          level: info
          reporter: ${{ env.REVIEWDOG_REPORTER }}

      - name: Run markdownlint
        uses: reviewdog/action-markdownlint@3667398db9118d7e78f7a63d10e26ce454ba5f58 # v0
        with:
          fail_on_error: true
          filter_mode: nofilter
          level: info
          reporter: ${{ env.REVIEWDOG_REPORTER }}
