---
name: Ansible Lint
on:  # yamllint disable-line rule:truthy
  - pull_request
  - push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check GitHub event type to determine reporter type
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
              echo "REVIEWDOG_REPORTER=github-pr-review" >> $GITHUB_ENV
          else
              echo "REVIEWDOG_REPORTER=github-check" >> $GITHUB_ENV
          fi

      - name: Run ansible-lint
        uses: reviewdog/action-ansiblelint@v1
        with:
          fail_level: none
          filter_mode: diff_context
          level: info
          reporter: ${{ env.REVIEWDOG_REPORTER }}
