---
name: Lint Python
on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - "**/*.py"

jobs:
  flake8:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.file-changes.outputs.changed-files }}
    strategy:
      matrix:
        python_version: ["3.9"]

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      - name: Modified files
        id: file-changes
        run: |
          echo "changed-files=$(git diff --name-only -r origin/${GITHUB_BASE_REF} origin/${GITHUB_HEAD_REF} | grep '\.py' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Check GitHub event type to determine reporter type
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
              echo "REVIEWDOG_REPORTER=github-pr-review" >> $GITHUB_ENV
          else
              echo "REVIEWDOG_REPORTER=github-check" >> $GITHUB_ENV
          fi

      - name: Set up Python environment
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Lint Python
        uses: reviewdog/action-flake8@b65981e158319f08cb7d0132f28bc0081e110adc # v3
        with:
          fail_on_error: false
          filter_mode: diff_context
          level: error
          flake8_args: ${{ steps.file-changes.outputs.changed-files }}
          reporter: ${{ env.REVIEWDOG_REPORTER }}
